# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
